// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using System;
using TrustchainCore.Repository;

namespace TrustchainCore.Migrations
{
    [DbContext(typeof(TrustDBContext))]
    partial class TrustDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("TrustchainCore.Model.Claim", b =>
                {
                    b.Property<int>("DatabaseID")
                        .ValueGeneratedOnAdd();

                    b.Property<uint>("Activate");

                    b.Property<short>("Cost");

                    b.Property<string>("Data");

                    b.Property<uint>("Expire");

                    b.Property<int>("Index");

                    b.Property<string>("Note");

                    b.Property<string>("Scope");

                    b.Property<int>("TrustDatabaseID");

                    b.Property<string>("Type");

                    b.HasKey("DatabaseID");

                    b.HasIndex("Index");

                    b.HasIndex("TrustDatabaseID");

                    b.ToTable("Claim");
                });

            modelBuilder.Entity("TrustchainCore.Model.KeyValue", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Key");

                    b.Property<byte[]>("Value");

                    b.HasKey("ID");

                    b.HasIndex("Key");

                    b.ToTable("KeyValues");
                });

            modelBuilder.Entity("TrustchainCore.Model.Package", b =>
                {
                    b.Property<int>("DatabaseID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Algorithm");

                    b.Property<byte[]>("Id");

                    b.HasKey("DatabaseID");

                    b.HasIndex("Id");

                    b.ToTable("Package");
                });

            modelBuilder.Entity("TrustchainCore.Model.ProofEntity", b =>
                {
                    b.Property<int>("DatabaseID")
                        .ValueGeneratedOnAdd();

                    b.Property<byte[]>("Receipt");

                    b.Property<long>("Registered");

                    b.Property<byte[]>("Source");

                    b.Property<int>("WorkflowID");

                    b.HasKey("DatabaseID");

                    b.HasIndex("Source");

                    b.HasIndex("WorkflowID");

                    b.ToTable("Proof");
                });

            modelBuilder.Entity("TrustchainCore.Model.Subject", b =>
                {
                    b.Property<int>("DatabaseID")
                        .ValueGeneratedOnAdd();

                    b.Property<byte[]>("Address");

                    b.Property<string>("Alias");

                    b.Property<byte[]>("ClaimIndexs");

                    b.Property<int>("TrustDatabaseID");

                    b.HasKey("DatabaseID");

                    b.HasIndex("Address");

                    b.HasIndex("TrustDatabaseID");

                    b.ToTable("Subject");
                });

            modelBuilder.Entity("TrustchainCore.Model.Timestamp", b =>
                {
                    b.Property<int>("DatabaseID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Algorithm");

                    b.Property<string>("Blockchain");

                    b.Property<int>("PackageDatabaseID");

                    b.Property<string>("Recipt");

                    b.Property<string>("Service");

                    b.Property<int>("Time");

                    b.HasKey("DatabaseID");

                    b.HasIndex("PackageDatabaseID");

                    b.ToTable("Timestamp");
                });

            modelBuilder.Entity("TrustchainCore.Model.Trust", b =>
                {
                    b.Property<int>("DatabaseID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Algorithm");

                    b.Property<byte[]>("Id");

                    b.Property<int?>("PackageDatabaseID");

                    b.HasKey("DatabaseID");

                    b.HasIndex("Id");

                    b.HasIndex("PackageDatabaseID");

                    b.ToTable("Trust");
                });

            modelBuilder.Entity("TrustchainCore.Model.WorkflowContainer", b =>
                {
                    b.Property<int>("DatabaseID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Data");

                    b.Property<string>("State");

                    b.Property<string>("Tag");

                    b.Property<string>("Type");

                    b.HasKey("DatabaseID");

                    b.HasIndex("State");

                    b.HasIndex("Type");

                    b.ToTable("Workflow");
                });

            modelBuilder.Entity("TrustchainCore.Model.Claim", b =>
                {
                    b.HasOne("TrustchainCore.Model.Trust")
                        .WithMany("Claims")
                        .HasForeignKey("TrustDatabaseID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TrustchainCore.Model.Package", b =>
                {
                    b.OwnsOne("TrustchainCore.Model.Identity", "Server", b1 =>
                        {
                            b1.Property<int>("PackageDatabaseID");

                            b1.Property<byte[]>("Address");

                            b1.Property<string>("Script");

                            b1.Property<byte[]>("Signature");

                            b1.ToTable("Package");

                            b1.HasOne("TrustchainCore.Model.Package")
                                .WithOne("Server")
                                .HasForeignKey("TrustchainCore.Model.Identity", "PackageDatabaseID")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });

            modelBuilder.Entity("TrustchainCore.Model.Subject", b =>
                {
                    b.HasOne("TrustchainCore.Model.Trust")
                        .WithMany("Subjects")
                        .HasForeignKey("TrustDatabaseID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TrustchainCore.Model.Timestamp", b =>
                {
                    b.HasOne("TrustchainCore.Model.Package")
                        .WithMany("Timestamps")
                        .HasForeignKey("PackageDatabaseID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TrustchainCore.Model.Trust", b =>
                {
                    b.HasOne("TrustchainCore.Model.Package")
                        .WithMany("Trusts")
                        .HasForeignKey("PackageDatabaseID");

                    b.OwnsOne("TrustchainCore.Model.Identity", "Issuer", b1 =>
                        {
                            b1.Property<int?>("TrustDatabaseID");

                            b1.Property<byte[]>("Address");

                            b1.Property<string>("Script");

                            b1.Property<byte[]>("Signature");

                            b1.ToTable("Trust");

                            b1.HasOne("TrustchainCore.Model.Trust")
                                .WithOne("Issuer")
                                .HasForeignKey("TrustchainCore.Model.Identity", "TrustDatabaseID")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("TrustchainCore.Model.TrustTimestamp", "Timestamp", b1 =>
                        {
                            b1.Property<int>("TrustDatabaseID");

                            b1.Property<string>("Algorithm");

                            b1.Property<byte[]>("Recipt");

                            b1.Property<string>("Timestamps");

                            b1.ToTable("Trust");

                            b1.HasOne("TrustchainCore.Model.Trust")
                                .WithOne("Timestamp")
                                .HasForeignKey("TrustchainCore.Model.TrustTimestamp", "TrustDatabaseID")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
